# This is a basic workflow to help you get started with Actions

name: Update Package Database

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "30 2 1 * *"

jobs:
  # pentestdb-git:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: archlinux
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: "Build"
  #       run: |
  #         useradd -ms /bin/bash build-user
  #         pacman -Syyu sudo base-devel git rust --needed --noconfirm
  #         cp pkgbuilds/x86_64/PenTestDB/PKGBUILD /tmp
  #         cd /tmp
  #         sudo -u build-user makepkg
  #         # cd -
  #         # cp /tmp/*.pkg.tar.zst x86_64/
  #     - name: "Upload PTDB build artifacts"
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: pentestdb
  #         path: /tmp/*.pkg.tar.zst
  #         retention-days: 5

  update-repo:
    # needs: ["pentestdb-git"]
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: pentestdb
      - name: Update repo DB
        run: |
          ls -la
          useradd -ms /bin/bash build-user
          pacman -Syu sudo base-devel --needed --noconfirm

          rm x86_64/*.pkg.tar.zst
          ls -la
          cp /tmp/*.pkg.tar.zst x86_64/

          source -u build-user ./update-lib.sh
          sudo -u build-user add_to_repo
      - name: commit new-pkg
        uses: EndBug/add-and-commit@v9.1.3
        with:
          add: "x86_64"
          author_name: "auto-updater"
          message: "automatic repo update"
          push: true
