# This is a basic workflow to help you get started with Actions

name: Update Package Nightly

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
    paths: ["pkgbuilds/**/*"]
  pull_request:
    branches: ["main"]
    paths: ["pkgbuilds/**/*"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "30 2 * * *"

jobs:
  pentestdb-git:
    runs-on: ubuntu-latest
    # container:
    #   image: archlinux
    steps:
      - uses: actions/checkout@v3
      # - name: which event trigger
      #   run: echo "github.event_name == '${{ github.event_name }}'"
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'pkgbuilds/x86_64/pentestdb-git/PKGBUILD'

      - if: ${{ (steps.changes.outputs.src == 'true') || (github.event_name == 'schedule') }}
        name: "Build"
        uses: docker://archlinux:latest
        with:
          args: |
            sh -c "
            useradd -ms /bin/bash build-user
            pacman -Syyu sudo base-devel git rust --needed --noconfirm
            cp pkgbuilds/x86_64/pentestdb-git/PKGBUILD /tmp
            cd /tmp
            sudo -u build-user makepkg"

      - if: ${{ (steps.changes.outputs.src == 'true') || (github.event_name == 'schedule') }}
        name: "Upload PTDB build artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: pentestdb-git
          path: /tmp/*.pkg.tar.zst
          retention-days: 5

  auto-desk-git:
    runs-on: ubuntu-latest
    # container:
    #   image: archlinux
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'pkgbuilds/x86_64/auto-desk-git/PKGBUILD'

      - if: ${{ (steps.changes.outputs.src == 'true') || (github.event_name == 'schedule') }}
        name: "Build"
        uses: docker://archlinux:latest
        with:
          args: |
            sh -c "
            useradd -ms /bin/bash build-user
            pacman-key --init
            pacman -Syyu sudo base-devel git rust xorg-server libx11 libxi libxext libxtst clang gcc iwd iw dbus pkgconf wpa_supplicant wireless_tools --needed --noconfirm
            cp pkgbuilds/x86_64/auto-desk-git/PKGBUILD /tmp
            cd /tmp
            sudo -u build-user makepkg"

      - if: ${{ (steps.changes.outputs.src == 'true') || (github.event_name == 'schedule') }}
        name: "Upload auto-desk build artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: auto-desk-git
          path: /tmp/*.pkg.tar.zst
          retention-days: 5

  update-repo:
    needs: ["pentestdb-git", "auto-desk-git"]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: "Download pentestdb-git"
        uses: actions/download-artifact@v3
        with:
          name: pentestdb-git
      - name: "Download auto-desk-git"
        uses: actions/download-artifact@v3
        with:
          name: auto-desk-git
      - name: Update repo DB
        uses: docker://archlinux:latest
        with:
          args: |
            sh -c "
            useradd -ms /bin/bash build-user
            pacman-key --init
            pacman -Syu sudo base-devel git --needed --noconfirm
            rm x86_64/*.pkg.tar.zst
            mv *.pkg.tar.zst x86_64/
            bash -c \"source ./update-lib.sh; add_to_repo\""
      - name: commit new-pkg
        uses: EndBug/add-and-commit@v9.1.3
        with:
          add: "x86_64"
          author_name: "auto-updater"
          # author_email: mail@example.com
          message: "automatic repo update"
          push: true
